export {default as HomePage} from './Homepage/HomePage';
export {default as SeriesPage} from './SeriesPage/SeriesPage';
export {default as MoviesPage} from './MoviesPage/MoviesPage';
export {default as PopularPage} from './PopularPage/PopularPage';
export {default as TrailerPage} from './TrailerPage/TrailerPage';
export {default as DetailPage} from './DetailPage/DetailPage';
export {default as SingInPage} from './SigninPage/SingInPage';
export {default as SingUpPage} from './SignUpPage/SingUpPage';
export {default as ErrorPage} from './ErrorPage/ErrorPage';
export {default as ProfilesPage} from './ProfilesPage/ProfilesPage';
export {default as ManageAccountPage} from './ManageAcountPage/ManageAccount';
export {default as ManageProfilesPage} from './ManageProfilePage/ManageProfilesPage'
export {default as ProfileSettingPage} from './ManageProfilePage/ProfileSettingPage/ProfileSettingPage'